import "bootstrap/dist/css/bootstrap.css";
import { Inter } from "next/font/google";
import "./globals.css"; // Global styles
import Navbar from './components/Navbar/Navbar'; // Updated path to Navbar.jsx
import Head from 'next/head'; // Import Head from next/head

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Toytopia Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
          crossOrigin="anonymous"
        />
      </Head>
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
