import { Inter } from "next/font/google";
import "./globals.css";

import "../node_modules/bootstrap/scss/bootstrap";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: " Toytopia Store ",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
